sudo: required
dist: trusty

addons.apt:
  update: true
  sources: google-chrome
  packages: google-chrome-stable

language: node_js

branches.only:
  - master
  - /^greenkeeper/.*$/

cache:
  directories:
    - node_modules

notifications.email: false

node_js: '12'

before_install:
  - npm install -g npm
  - npm install -g greenkeeper-lockfile@1
install:
  - npm install  
before_script:
  - greenkeeper-lockfile-update
script:
  - npm run build
  - npm run test
after_script:
  - greenkeeper-lockfile-upload

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist/ngx-imageviewer
  on:
    branch: master  

after_success:
  - npm run travis-deploy-once "npm run semantic-release"
