language: node_js
dist: xenial

node_js: 10
cache: npm

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

install:
  npm install

jobs:
  include:
    - stage: "Test"
      name: "Test"
      script:
       - npm run build
       - npm run test
    - stage: "Docs"
      name: "Docs"
      script:
        - npm run build
        - npm run build:docs
      deploy:
        provider: pages
        skip_cleanup: true
        keep_history: true
        github_token: $GITHUB_TOKEN
        local_dir: dist/ngx-imageviewer-app
        on: 
          branch: master
    - stage: "Build"
      name: "Build"
      script:
        - npm run build
      after_success:
       - npm run semantic-release
