sudo: required
dist: trusty

addons.apt:
  update: true
  sources: google-chrome
  packages: google-chrome-stable

language: node_js

branches.only:
  - master
  - /^greenkeeper/.*$/

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.npm

notifications.email: false

node_js: '8'

before_install:
  - yarn global add greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
script:
  - yarn build:lib
  - yarn test
  - yarn build:docs
  - cp LICENSE README.md dist/ngx-imageviewer/
after_script:
  - greenkeeper-lockfile-upload

after_success:
  - yarn travis-deploy-once "yarn semantic-release"
